kind: Service
apiVersion: v1
metadata:
  name: travel-agency-service
spec:
  selector:
    app: travel-agency-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: travel-agency-service
spec:
  selector:
    matchLabels:
      app: travel-agency-service
  replicas: 2
  template:
    metadata:
      labels:
        app: travel-agency-service
    spec:
      containers:
        - name: travel-agency-service
          image: travel-agency-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8002