kind: Service
apiVersion: v1
metadata:
  name: client-service
  labels:
    app: client-service
spec:
  selector:
    app: client-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: client-service
  labels:
    app: client-service
spec:
  selector:
    matchLabels:
      app: client-service
  replicas: 1
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
        - name: client-service
          image: client-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001